version: 2.1

executors:
  gpu_small:
    parameters:
      dlc:
        type: boolean
        default: false
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
      docker_layer_caching: << parameters.dlc >>
    resource_class: gpu.nvidia.small

commands:
  purge-dlc:
    steps:
      - run: docker system prune --force --volumes --all

jobs:
  build:
    parameters:
      parallel:
        type: integer
        default: 1
    parallelism: << parameters.parallel >>
    executor:
      name: gpu_small
      dlc: true
    steps:
      - run: lsb_release -a
      - run: uname -a
      - run: docker info
      - checkout
      - purge-dlc
      - run: docker image build -t kelvintaywl/large-image -f Dockerfile.xlarge .
  pull:
    executor:
      name: gpu_small
      dlc: true
    steps:
      - purge-dlc
      - run: docker pull kelvintaywl/large:15GB
      - run: docker pull slightlytyler/large-image-test:latest

workflows:
  main:
    jobs:
      - build
      - pull:
          requires:
            - build
